/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c4c17e5d-f5bb-433c-8b1a-29d7bb74e974",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ServiceBot_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
